### ISSUE TITLE
Error handling using try / catch

### ISSUE THREAD

**Issue by ilbrando** [agiledigital/typed-redux-saga#147]
Great product, finally making redux saga typesafe 😀

It appears to me that try / catch error handling does not work. Is that right? I have this scenario:

```ts
// saga function:
try {
  const result = yield* callBackend();
  yield* put(success());
} catch {
  yield* put(error());
}

// callBackend:
return yield* call(function_that_uses_fetch)
```
The function that uses fetch throws an error, but it is not caught in the catch clause.
Is it possible to make this work?

**Comment by danielnixon** [comment]
As far as I can tell this scenario works as you'd expect. I've just verified with this example:

```ts
const throws = (): never => {
  throw new Error("whoops");
};

function* callThrows(): SagaGenerator<unknown> {
  return yield* call(throws);
}

export function* foo(): SagaIterator<void> {
  try {
    yield* callThrows();
  } catch (e) {
    console.log(e instanceof Error ? e.message : JSON.stringify(e));
  }
}
```

`whoops` is logged to the console as you'd expect.

I suspect something else is going on in your case.

**Comment by danielnixon** [comment]
Closing this for now to keep things tidy. @ilbrando please reopen or create a new ticket if you can see what is different between your case and the example I posted above.
