### ISSUE TITLE
eslint not playing nice with tsconfig paths

### ISSUE THREAD

**Issue by danielnixon** [agiledigital/typed-redux-saga#248]
Note these paths from `tsconfig.json`:

```
    "baseUrl": ".",
    "paths": {
      "typed-redux-saga": ["."],
      "typed-redux-saga/macro": ["./macro"],
      "typed-redux-saga/effects-for-action-type": ["./effects-for-action-type"]
    }
```

It seems like eslint doesn't understand these, so for example tsc is happy with this, but eslint isn't:

```ts
import * as Effects from "typed-redux-saga/macro";
```

**Comment by afonsopbarros** [comment]
also can't import from typed-redux-saga/macro

**Comment by danielnixon** [comment]
cc @gilbsgilbs

**Comment by gilbsgilbs** [comment]
Yeah, that's the type of issues I was afraid of. Node packaging is such a mess, that puts me on nerves every time :disappointed: .

So I think there are two issues:
- TypeScript doesn't look for the proper type definitions. This is easy to fix.
- Node doesn't look for the proper module. This is easy to address in Node 14 (with the new `exports` field in `package.json`), but is a mess with older versions. IIRC, the only way to have this working without making a different package for the macro is to build the macro in the root directory of the project :man_facepalming: . I'll look into it.
