### ISSUE TITLE
Context "this" is not correctly resolved.

### ISSUE THREAD

**Issue by NorbertBodziony** [agiledigital/typed-redux-saga#257]
In use with some external libraries `this` seems to be not resolved correctly and causes error.
![image](https://user-images.githubusercontent.com/38857779/96348749-494a7300-10ab-11eb-87d5-1c88975c641f.png)
Above case resulted using https://github.com/ethers-io/ethers.js/ library.
```
  const signer = yield* call(getSigner)
  const balance = yield* call(signer.getBalance)
```
`getBalance` should return `BigNumber` but instead fails.

Refactoring function into Promise solves this problem.

**Comment by danielnixon** [comment]
Does it work with raw redux-saga?

**Comment by NorbertBodziony** [comment]
It does not.

**Comment by NorbertBodziony** [comment]
Update: Just found out that you can pass context 
```
  const balance = yield* call([signer, signer.getBalance])
```
Now works as expected.
