### ISSUE TITLE
Typing yield* call of a generic function

### ISSUE THREAD

**Issue by ywongweb** [agiledigital/typed-redux-saga#258]
Thank you for this great library! 

Does anyone know how to type the following saga `call`

// React View component equivalent
```
    apolloClient.query<GetAppVersionQuery>({query: getAppVersion, variables: { platform: Platform.IOS }}).then(res => {
      console.log(res)  // res is type GetAppVersionQuery
    })
```

In `typed-redux-saga`
```
    const { query } = apolloClient
    const response = yield* call(query, { query: getAppVersion, variables: { platform: Platform.IOS }})
    // response is type any, how to set return type to GetAppVersionQuery?
```

The original `query` has the type of
`const query: <T=any, TVariables=Record<string, any>>(options: QueryOptions<TVariables, T>) => Promise<ApolloQueryResult<T>>`

Thank you

**Comment by gilbsgilbs** [comment]
I also noticed this kind of issues with `call` and generics a long time ago. Even in more basic scenarios, Typescript just completely fails to infer a type. If I recall correctly it was more a typescript issue than an actual typing issue (but I may be wrong).

I personally avoid passing extra arguments at all to `call` and rather rely on the following type-safe "workaround" (which I actually find more readable than the "intended" way):

```typescript
const response = yield* call(
  () => query<GetAppVersionQuery>({ ... }})
)
```

**Comment by ywongweb** [comment]
Thank you so much for this great workaround!
