### ISSUE TITLE
call effect does not infer the type

### ISSUE THREAD

**Issue by henrikra** [agiledigital/typed-redux-saga#27]
Tested with 
TS: 3.7.2
typed-redux-saga: 1.0.6

How to reproduce?

```ts
import { select, call } from 'typed-redux-saga';


function someApiCall(): number {
	return 1;
}
function someSelect(): number {
	return 1;
}

export function* doStuff() {
	const result = yield* call(someApiCall)
	
	// variable `result` is still any
	result.lol();


	const selectResult = yield* select(someSelect)

	// gives error as expected
	selectResult.lol();
}

```

As you can see from the example code the the `select` effect infers correct type but `call` does not. Where is the problem? 🤔

**Comment by mincedmit** [comment]
@henrikra  Does it work if your API call is modified to return a resolved Promise i.e. `return Promise.resolve(1)` ?

**Comment by henrikra** [comment]
Nope

**Comment by danielnixon** [comment]
Could you formulate this as a dtslist `$ExpectType` failure in index.test.ts?

**Comment by danielnixon** [comment]
I've added the tests and they all work. It could be that this was fixed accidentally by a subsequent change. I'll close this issue for now. @henrikra please reopen or create another issue if this is still an issue.

```
  // $ExpectType number
  yield* Effects.call(function(): number {
    return 22;
  });

  // $ExpectType number
  yield* Effects.call(() => 22);

  // $ExpectType number
  yield* Effects.call(function(): Promise<number> {
    return Promise.resolve(22);
  });

  // $ExpectType number
  yield* Effects.call(function*(): SagaIterator<number> {
    yield* Effects.take(chan);
    return 22;
  });
```

**Comment by henrikra** [comment]
I have now tried again with TypeScript `3.9.6` and typed-redux-saga `1.2.0`.

Still same issues with the code I have posted in the starting post. `select` infers correct type but `call` does not.

Here I hover on `result` and it is `any`

![image](https://user-images.githubusercontent.com/12229968/89382659-df553b00-d703-11ea-9ff0-dc2c2ff6a7da.png)

And here you can see that `selectResult` is `number` as it should

![image](https://user-images.githubusercontent.com/12229968/89382696-ed0ac080-d703-11ea-9e6d-6ee3657f8142.png)

**Comment by danielnixon** [comment]
Hi @henrikra 

I've just added more tests to confirm that your example infers `number` as expected. See https://github.com/agiledigital/typed-redux-saga/commit/d33ff9e55a7e3438ccd81012484e6b883bb646c5

Something else must be going on in your case. Maybe it's something else in your imports, maybe it's something in your tsconfig, I don't know. Please do one of the following or I can't help you:

1. Submit a PR to fix the issue
2. Submit a PR that demonstrates the issue using dtslist $ExpectType failure, as I asked for here https://github.com/agiledigital/typed-redux-saga/issues/27#issuecomment-632947824
3. Create a minimal reproduction in another repo so I can see what is really going on

**Comment by danielnixon** [comment]
Closing this for now to keep things tidy. @henrikra please reach out if you create a minimal reproduction.
