### ISSUE TITLE
Make PR about this to redux-saga?

### ISSUE THREAD

**Issue by henrikra** [agiledigital/typed-redux-saga#4]
Since this library is very simple wrapper could you make PR about these changes to redux-saga it self so everyone would have these wonderful benefits? :)

**Comment by parkerault** [comment]
I don't think this is ever going to get into redux-saga since it breaks backwards compatibility and only implements a few effects. It would be nice to get a link to it from the documentation though.

**Comment by henrikra** [comment]
Ah because every would have to use `yield*`?

**Comment by parkerault** [comment]
Yep, and this just scratches the surface of the saga API. I do use it everywhere though, since I mostly just need a typed `call` and `select`.

**Comment by parkerault** [comment]
They just wrap the redux-saga effects in a generator so they can use the stricter types from typescript 3.7.

**Comment by danielnixon** [comment]
Closing this as @gilbsgilbs has started the conversation at https://github.com/redux-saga/redux-saga/issues/2008
