### ISSUE TITLE
How do you type all? 

### ISSUE THREAD

**Issue by Moejoe90** [agiledigital/typed-redux-saga#7]
do you have an idea on how to get safely typed generators that are under the `all` effect?

**Comment by dionshihk** [comment]
I proposed a PR about this issue, hope to be merged in next version.

https://github.com/agiledigital/typed-redux-saga/pull/9

**Comment by danielnixon** [comment]
@Moejoe90 I'm closing this as @dionshihk 's PR is in the latest version. Let me know how you go.
